name: test

on:
    push: 
        branches: #nivel de rama
        - "main" # el nombre de la rama y puede ir una lista de ramas
env: 
  USER_REPOSITORY: Jaun

jobs:
    test_ads: # nombre de nuestro jobs par hacer las pruebas necesitamos una maquina virtual, debemos de indicarle que version de linux
        #runs-on: ubuntu-18.04 # ESto es pa que haya error  entonces ahora toca definir pasos usar inferir a 18.04 o latest porque coloca la ultima version y luego peude venir una version no estable 
        runs-on: ubuntu-20.04
        steps: # lista de pasos podemos tener varios. tienen un nombre y que s evana  ejecutar
            - name: Show message # no hay problema con el name ya que es una estructura anidada
              run: echo "Juanes 20/05/24 " #LOS ESPACIOS SON MUY IMPORTANTES :v
            - name: Show secret
              run: echo ${{secrets.OTRASECRET}}

            - name: Show variable in file
              run: echo ${{env.USER_REPOSITORY}}

            - name: Show variable in actions
              run: echo ${{vars.OTHERVAR}}

            - uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            
            - name: Test setup node
              run: node --version